name: "Test"

on:
  - "push"

jobs:
  test:
    name: "Test python-versions output (${{ matrix.os }})"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"

    steps:
      - name: "Setup Python"
        id: "setup-python"
        uses: "kurtmckee/setup-python@output-python-versions-issue-606"
        with:
          python-version: |
            pypy3.9
            3.7
            3.8
            pypy3.8
            3.9
            3.12-dev
            3.10
            3.11

      - name: "Show installed Python versions"
        shell: bash
        run: |
          echo "${{ steps.setup-python.outputs.python-versions }}"
